version: '3.2'

services:

  aiohttpdemo_slackbot_app: &app
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: aiohttpdemo_slackbot
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
    restart: always
    volumes:
      - .:/app:delegated
    ports:
      - 8080:8080
      - 8081:8081
    command: adev runserver ./aiohttpdemo_slackbot/__main__.py -p 8080

  test:
    <<: *app
    container_name: aiohttpdemo_slackbot_test
    ports:
      - 8082:8082
    command: make _test
